# Generated by Django 2.1.7 on 2019-03-24 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dang_ky_hoc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbldangkyhoc',
            old_name='nagy_dang_ky',
            new_name='ngay_dang_ky',
        ),
    ]
