# Generated by Django 2.1.7 on 2019-03-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dang_ky_hoc', '0002_auto_20190324_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbldangkyhoc',
            name='hoten',
        ),
        migrations.RemoveField(
            model_name='tbldangkyhoc',
            name='khoahoc',
        ),
        migrations.RemoveField(
            model_name='tbldangkyhoc',
            name='sdt',
        ),
        migrations.AddField(
            model_name='tbldangkyhoc',
            name='dien_thoai',
            field=models.CharField(default='', max_length=264),
        ),
        migrations.AddField(
            model_name='tbldangkyhoc',
            name='ho_ten',
            field=models.CharField(default='', max_length=264),
        ),
        migrations.AddField(
            model_name='tbldangkyhoc',
            name='khoa_hoc',
            field=models.CharField(default='', max_length=264),
        ),
        migrations.AlterField(
            model_name='tbldangkyhoc',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tbldangkyhoc',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbldangkyhoc',
            name='ngay_dang_ky',
            field=models.DateField(),
        ),
    ]
