# Generated by Django 2.1.7 on 2019-03-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblDangKyHoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khoahoc', models.CharField(default='', max_length=100)),
                ('hoten', models.CharField(default='', max_length=100)),
                ('sdt', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('nagy_dang_ky', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
