# Generated by Django 2.1.7 on 2019-03-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThongTinKhachHang',
            fields=[
                ('ma_KH', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('ho_ten', models.CharField(max_length=150, unique=True)),
                ('gioi_tinh', models.CharField(choices=[('NAM', 'Nam'), ('NU', 'Nữ'), ('KHAC', 'Khác')], default='NAM', max_length=4)),
                ('ngay_sinh', models.DateField()),
                ('quoc_tinh', models.CharField(max_length=30)),
                ('so_cmnd_cccd_hc', models.CharField(max_length=30)),
                ('ngay_cap', models.DateField()),
                ('dia_chi_thuong_tru', models.TextField()),
                ('dia_chi_hien_tai', models.TextField()),
                ('sdt', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('so_nguoi_phu_thuoc', models.PositiveIntegerField(default=0)),
                ('trinh_do_hoc_van', models.CharField(choices=[('TDH', 'Trên đại học'), ('DH', 'Đại học'), ('CD', 'Cao đẳng'), ('TC', 'Trung cấp'), ('KH', 'Khác')], default='TDH', max_length=3)),
                ('Loai_nha_o', models.CharField(choices=[('BT', 'Biệt thự'), ('NLK', 'Nhà liền kề'), ('ND', 'Nhà đất'), ('CC', 'Chung cư'), ('KH', 'Khác')], default='BT', max_length=2)),
                ('hinh_thuc_so_huu_nha', models.CharField(choices=[('NR', 'Nhà riêng'), ('NDT', 'Nhà đi thuê'), ('NTM', 'Nhà thuê mua'), ('OCBM', 'Ở chung với bố mẹ(trừ trường hợp bô mẹ cũng đi thuê nhà)'), ('NMTG', 'Nhà mua trả chậm'), ('KHAC', 'Khác')], default='NR', max_length=4)),
                ('tinh_trang_hon_nhan', models.CharField(choices=[('DT', 'Độc thân'), ('DCGD', 'Đã có gia đình'), ('LD', 'Ly dị'), ('G', 'Goá'), ('LT', 'Ly thân'), ('KH', 'Khác')], default='DT', max_length=4)),
            ],
        ),
    ]
