# Generated by Django 2.1.7 on 2019-03-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('price', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(default='', max_length=50, upload_to='')),
            ],
        ),
    ]
